services:

  app:
    build:
      context: ..
      dockerfile: docker/app.dockerfile
      target: production
      args:
        - GO_VERSION=${GO_VERSION}
        - BUFFALO_VERSION=${BUFFALO_VERSION}
        - USERNAME=${USERNAME}
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - USERNAME=${USERNAME}
